apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wi8nqey7e-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:29cab9df532b4d85efaac33a1ac1654265011a0a@sha256:31f4b4c1190e6ff8918ffd9253c8110f28b3962562f86b0b55e44ce7b738f09c
          name: container-image
